[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/64/large/1a21cc7854fbdeded52cd48dac77a2b3_default.png'
alt = 'Avatar of nadah95'
{{< /image >}}
nadah95'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/46/large/bac4fb8315a046cb4e8e9a5e1da788a0.jpeg'
alt = 'Avatar of Sayed Adel'
{{< /image >}}
Sayed Adel'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/112/large/44510a051d515a1ac410fd98a3e63422_default.png'
alt = 'Avatar of bls868327'
{{< /image >}}
bls868327'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/125/large/2a1c93df32661fd47e215f48146c4037.jpeg'
alt = 'Avatar of Juan Pablo Duque'
{{< /image >}}
Juan Pablo Duque'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/106/large/7642f87b71c440238974dbbccb9bc85d_default.png'
alt = 'Avatar of asoretzu'
{{< /image >}}
asoretzu'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/135/large/59ad5b2b5c935e1ad9edcfe70f6545c1.jpeg'
alt = 'Avatar of Yeimi'
{{< /image >}}
Yeimi'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/173/large/4a21daa58a4f86783101730947601d2b.png'
alt = 'Avatar of Linderman Dominguez'
{{< /image >}}
Linderman Dominguez'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/2/large/ff1cb97cef3163bc6f0f6c5d17bcf37b.jpg'
alt = 'Avatar of scientific-python'
{{< /image >}}
scientific-python'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/143/large/d84181fc314a335096fef91bac4192f9.png'
alt = 'Avatar of Riva Quiroga'
{{< /image >}}
Riva Quiroga'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/131/large/d69601adfc914c8f475e3c5f8b3733fc.png'
alt = 'Avatar of Oriol Abril-Pla'
{{< /image >}}
Oriol Abril-Pla'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/139/large/06cbf9ceee9480c0d9fbaf6e81533773_default.png'
alt = 'Avatar of pyjavo'
{{< /image >}}
pyjavo'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/129/large/e5a752ffaf7037cdb541c3b36ae20fec.jpeg'
alt = 'Avatar of Juanita Gomez'
{{< /image >}}
Juanita Gomez'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/159/large/08ba42ad7a86bb65dfb892a21b52dc0c.png'
alt = 'Avatar of Gonzalo Peña-Castellanos'
{{< /image >}}
Gonzalo Peña-Castellanos'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/137/large/6fe2d4efc99cc97041712b4439bd5bba.jpeg'
alt = 'Avatar of Ali Faraji'
{{< /image >}}
Ali Faraji'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/123/large/d45f01d8d7a26eabbd4a26d6d73bf040.jpeg'
alt = 'Avatar of Saeed Foroutan'
{{< /image >}}
Saeed Foroutan'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/193/large/c3251f5e0c70c3cc3d0197ed677e4a6c.png'
alt = 'Avatar of Claire Filtz'
{{< /image >}}
Claire Filtz'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/157/large/5dd77d6fa1b76e93323200a3c15c5e8c.jpeg'
alt = 'Avatar of Ariane Djeupang J'
{{< /image >}}
Ariane Djeupang J'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/163/large/64e117e122f9a70fbf08b7baf0b9365d.jpeg'
alt = 'Avatar of Filippo Balzaretti'
{{< /image >}}
Filippo Balzaretti'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/44/large/3bb9c6b3fe518ea5932fae2418c55d17.JPG'
alt = 'Avatar of Atsushi Sakai'
{{< /image >}}
Atsushi Sakai'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/12/large/4e3e621d788e1770f3ca9e243f844aae.png'
alt = 'Avatar of Ralf Gommers'
{{< /image >}}
Ralf Gommers'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/102/large/ec521bfc06ede0c7a0c6f75a22a84261_default.png'
alt = 'Avatar of albert.steppi'
{{< /image >}}
albert.steppi'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/110/large/38cf3c89f49049eb2003d04743eb3a42_default.png'
alt = 'Avatar of yamunofu'
{{< /image >}}
yamunofu'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/116/large/041631f9121187b9f0bf63135f9903b2_default.png'
alt = 'Avatar of justcontributor'
{{< /image >}}
justcontributor'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/187/large/156cbfa6517976663ca7a221c1d0a6e6.jpeg'
alt = 'Avatar of Kangwon Lee'
{{< /image >}}
Kangwon Lee'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/114/large/8563b3d329fb38c0df97dac8f3d2fdfa_default.png'
alt = 'Avatar of miknai'
{{< /image >}}
miknai'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/96/large/b6a71b775830276cfa911464f61b28f8_default.png'
alt = 'Avatar of joohyung'
{{< /image >}}
joohyung'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/153/large/a6a758dee542f0037172806471eba2a8.jpeg'
alt = 'Avatar of Kangwon Lee'
{{< /image >}}
Kangwon Lee'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/82/large/93a69169a60c740ab33521a423459aba.jpg'
alt = 'Avatar of Julio Batista Silva'
{{< /image >}}
Julio Batista Silva'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/165/large/9a2f43785099c0b45aa1576d9230c1ef.png'
alt = 'Avatar of Helder Geovane Gomes de Lima'
{{< /image >}}
Helder Geovane Gomes de Lima'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/24/large/86c090db47578559b8a4e26bd0b1a82d.jpeg'
alt = 'Avatar of Melissa Weber Mendonça'
{{< /image >}}
Melissa Weber Mendonça'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/10/large/51dfb38e63e83087866c74630db6abad_default.png'
alt = 'Avatar of villares'
{{< /image >}}
villares'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/94/large/09cdbf547db3e2413bb8f115a063e575.png'
alt = 'Avatar of Getúlio Silva'
{{< /image >}}
Getúlio Silva'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/104/large/0e46bbb05848c7ed4b34e025f344c3d2_default.png'
alt = 'Avatar of aerwy'
{{< /image >}}
aerwy'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/161/large/45e76aee57d7b3b6fc60d4c0551f411a.jpeg'
alt = 'Avatar of Rajasekaran Karunanithi'
{{< /image >}}
Rajasekaran Karunanithi'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/98/large/4f6f4e335559e2f14d2d8a08f22b1251_default.png'
alt = 'Avatar of hellosarahwang'
{{< /image >}}
hellosarahwang'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/100/large/73184aa58a8c2f74b2d5c938a03cb7ce_default.png'
alt = 'Avatar of jasonliX'
{{< /image >}}
jasonliX'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/50/large/bb779dcd4219fd0fcee5caa168da0a9e_default.png'
alt = 'Avatar of tianxing'
{{< /image >}}
tianxing'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/78/large/748aeac707488e186127556d65193ea1_default.png'
alt = 'Avatar of Qiyu8'
{{< /image >}}
Qiyu8'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/76/large/c79f6a29b824d97345e9dffaa2dda31d_default.png'
alt = 'Avatar of ktKongTong'
{{< /image >}}
ktKongTong'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/8/large/8c0cfcf73fc35e35b8c1bc209b0e8a20_default.png'
alt = 'Avatar of Aaron212'
{{< /image >}}
Aaron212'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/38/large/6045d174952b974e3512716eac0d40b3_default.png'
alt = 'Avatar of we****n@me***i.com'
{{< /image >}}
we****n@me***i.com'''
link = 'https://scientific-python-translations.github.io/contributors/'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://production-enterprise-static.cf-downloads.crowdin.com/avatar/88/large/e2e254299d505f53967a59fa23bcc157_default.png'
alt = 'Avatar of blueskyson'
{{< /image >}}
blueskyson'''
link = 'https://scientific-python-translations.github.io/contributors/'